apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    name: webui
    nodePort: 30001
    protocol: TCP
  - port: 8888
    name: popek
    nodePort: 30002
    protocol: TCP
  selector:
    app: hello-world
